package com.suromo.material.ui.theme

import androidx.compose.ui.graphics.Color


//浅色主题颜色
val light_primary = Color(0xFF795557)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDADB)
val light_onPrimaryContainer = Color(0xFF2E1416)
val light_secondary = Color(0xFF685B5C)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFF0DEDE)
val light_onSecondaryContainer = Color(0xFF22191A)
val light_tertiary = Color(0xFF695C4E)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFF1E0CD)
val light_onTertiaryContainer = Color(0xFF231A0F)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1E1B1B)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1E1B1B)
val light_surfaceVariant = Color(0xFFEAE0E0)
val light_onSurfaceVariant = Color(0xFF4B4545)
val light_outline = Color(0xFF7D7575)
val light_inverseSurface = Color(0xFF333030)
val light_inverseOnSurface = Color(0xFFF6EFEE)
val light_inversePrimary = Color(0xFFE9BBBD)
val light_surfaceTint = Color(0xFF795557)

//深色主题颜色
val dark_primary = Color(0xFFE9BBBD)
val dark_onPrimary = Color(0xFF46282A)
val dark_primaryContainer = Color(0xFF5F3E40)
val dark_onPrimaryContainer = Color(0xFFFFDADB)
val dark_secondary = Color(0xFFD3C3C3)
val dark_onSecondary = Color(0xFF382E2E)
val dark_secondaryContainer = Color(0xFF4F4444)
val dark_onSecondaryContainer = Color(0xFFF0DEDE)
val dark_tertiary = Color(0xFFD4C4B2)
val dark_onTertiary = Color(0xFF392F22)
val dark_tertiaryContainer = Color(0xFF504537)
val dark_onTertiaryContainer = Color(0xFFF1E0CD)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFB4AB)
val dark_background = Color(0xFF1E1B1B)
val dark_onBackground = Color(0xFFE8E1E0)
val dark_surface = Color(0xFF1E1B1B)
val dark_onSurface = Color(0xFFE8E1E0)
val dark_surfaceVariant = Color(0xFF4B4545)
val dark_onSurfaceVariant = Color(0xFFCEC4C4)
val dark_outline = Color(0xFF978F8F)
val dark_inverseSurface = Color(0xFFE8E1E0)
val dark_inverseOnSurface = Color(0xFF333030)
val dark_inversePrimary = Color(0xFF795557)
val dark_surfaceTint = Color(0xFFE9BBBD)

//通用颜色
val seed = Color(0xFFAE8587)
val CustomColor1 = Color(0xFFBBC6E2)
val light_CustomColor1 = Color(0xFF2F5DA8)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFD7E2FF)
val light_onCustomColor1Container = Color(0xFF001A40)
val dark_CustomColor1 = Color(0xFFACC7FF)
val dark_onCustomColor1 = Color(0xFF002F68)
val dark_CustomColor1Container = Color(0xFF0B458E)
val dark_onCustomColor1Container = Color(0xFFD7E2FF)